version: '3.8'

services:
   backend:
    build: ./backend
    environment:
      PORT: 3000
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGHOST: postgres
      PGPORT: 5432
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      AUTH_API_URL: ${AUTH_API_URL}
      LEAD_API: ${LEAD_API}
      ACCOUNT_API: ${ACCOUNT_API}
      AUTHORIZATION: ${AUTHORIZATION}
      USER_AGENT: ${USER_AGENT}
      JWT_SECRET: ${JWT_SECRET}
      OCLIENT_ID: ${OCLIENT_ID}
      OCLIENT_SECRET: ${OCLIENT_SECRET}
    ports:
      - "3000:3000"
   frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: http://13.53.122.130:3000
    ports:
      - "80:80"

volumes:
  pg_data: